### PR TITLE
GSI speedup, add the fix/ directory, bug fixes and others

### PR DESCRIPTION
**Pull request by guoqing-noaa**
< Changes here are mainly reflected by hash updates for different components >  

use 2 OMP threads, kjet specific optimization and parallel netcdf to speed up GSI run  
change cp_vrfy to ln_vrfy for GSI jobs  
changes in FV3LAM namelist
add $HYBENSMEM_NMIN which sets the minimum number of ensembles required for a hybrid GSI analysis
more control on wgrib2 jobs
clean up outdated variables in exregional_run_analysis.sh
turn off l2rw DA through gsiparm.anl
update devbuild.sh to be able to determine HPC platforms automatically
bug fixes on rrfs_utl, pygraf, gsi, etc.

Add the fix/ directory to regional_workflow
 - GSI  fix files under fix/gsi
 - UPP  fix files under fix/upp
 - CRTM fix files under fix/crtm
 - change scripts, config.sh*, etc accordingly
    
Add Init.sh   
 - initialize fix/ so that links to binary/large fix files work at different HPC platforms
 - install pre-commit git hook to prevent binary/large fix files themselves to be committed   

Add fix_rrfs_locations.sh   
 - set the FIX_RRFS locations at differnt HPC platforms          

AIRCRAFT_REJECT, SFCOBS_USELIST       
 - default to use fix files under FIX_GSI unless a path specified in config.sh       

Add $TESTBED_FIELDS_FN (files are under FIX_UPP)        
 - different testbed_fields files for different applications     
 - if empty string, no bgsfc output

### CODE REVIEW

**Comment by guoqing-noaa** [comment]
For information, relevant PRs to different components:

regional_workflow: https://github.com/NOAA-GSL/regional_workflow/pull/210  
GSI:  https://github.com/NOAA-GSL/GSI/pull/4

**Review by cshartsough — APPROVED** [review]
Looks good, nothing to comment on.  Thanks.

**Review by cshartsough — APPROVED** [review]

**Review by EdwardColon-NOAA — APPROVED** [review]
Looks good but wcoss2 will need to be added to the machine-specific options at some point in devbuild.sh.

**Review by AnnetteGibbs-NOAA — APPROVED** [review]
Looks good.

**Pull request merged**
